parse-url: https://www.bloomberg.com/graphics/2024-us-election-results/
first-candidate-container: div.win-dem.svelte-1b5y444
second-candidate-container: div.win-rep
first-candidate-name: Harris
second-candidate-name: Trump
update-delay: 600000